name: Build SunamoDevCode

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoDevCode
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoDevCode/SunamoDevCode.csproj

    - name: Build
      run: dotnet build SunamoDevCode/SunamoDevCode.csproj --configuration Release --no-restore

  test:
    name: Test SunamoDevCode.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoDevCode.Tests/SunamoDevCode.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoDevCode.Tests/SunamoDevCode.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoDevCode.Tests/SunamoDevCode.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
